---
- name: Creating site directory
  file: path={{ site_directory }}/site
        state=directory
        mode=0775

- name: Creating cache directory
  file: path={{ site_directory }}/site/cache
        state=directory
        mode=0775

- name: Uploading site data
  copy: src={{ local_site_directory }}/data
        dest={{ site_directory }}/site/data

- name: Uploading site scripts
  copy: src={{ local_site_directory }}/scripts
        dest={{ site_directory }}/site/scripts

- name: Uploading site styles
  copy: src={{ local_site_directory }}/styles
        dest={{ site_directory }}/site/styles

- name: Uploading site templates
  copy: src={{ local_site_directory }}/templates
        dest={{ site_directory }}/site/templates

- name: Uploading site configuration file
  copy: src={{ local_site_directory }}/config.php
        dest={{ site_directory }}/site/config.php

- name: Configuring time zone
  lineinfile: dest={{ site_directory }}/site/config.php
              regexp="^define\('_TIMEZONE', '.*'\);"
              line="define('_TIMEZONE', '{{ timezone }}');"

- name: Configuring database host
  lineinfile: dest={{ site_directory }}/site/config.php
              backrefs=yes
              regexp="^(\s+)'host'\s=>\s'.*',"
              line="\1'host' => '{{ database.host }}',"

- name: Configuring database username
  lineinfile: dest={{ site_directory }}/site/config.php
              backrefs=yes
              regexp="^(\s+)'user'\s=>\s'.*',"
              line="\1'user' => '{{ database.username }}',"

- name: Configuring database password
  lineinfile: dest={{ site_directory }}/site/config.php
              backrefs=yes
              regexp="^(\s+)'pass'\s=>\s'.*',"
              line="\1'pass' => '{{ database.password }}',"

- name: Configuring database name
  lineinfile: dest={{ site_directory }}/site/config.php
              backrefs=yes
              regexp="^(\s+)'name'\s=>\s'.*'"
              line="\1'name' => '{{ database.name }}'"

